name: hello-world
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Build app
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with: 
          name: code
          path: .