name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with: 
          name: code
          path: .

     
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps: 
      - name: Download Repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Build app
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with: 
          name: build
          path: .

